#데이터분석, 머신러닝

## Numpy 라이브러리 불러오기
- https://numpy.org/doc/stable/

In [1]:
import numpy as np   # np는 약어
print(np.__version__)

1.22.4


In [2]:
import numpy
print(numpy.__version__)

1.22.4


## 리스트를 배열로 변환


In [4]:
temp = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
temp_array = np.array(temp)
print(temp)          #리스트는 쉼표가 있음
print(temp_array)    #배열은 쉼표가 없음

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
print(type(temp))      #리스트
print(type(temp_array))  # 배열
print(temp_array.shape)
print(temp_array.ndim)


<class 'list'>
<class 'numpy.ndarray'>
(10,)
1


- 참조: https://numpy.org/doc/stable/reference/index.html#reference

In [6]:
temp_array[1]

2

In [8]:
temp_array[-1]

10

## 사칙연산

In [85]:
score1 = [10, 15, 40, 50, 80]
score2 = [30, 40, 70, 50, 100]

score1+score2

[10, 15, 40, 50, 80, 30, 40, 70, 50, 100]

In [86]:
score1_arr = np.array(score1)  #리스트를 사칙연산이 가능한 numpy로 변행해서 연산함.
score2_arr = np.array(score2)

result = score1_arr + score2_arr

In [87]:
np.min(result)

40

In [88]:
np.max(result)

180

In [89]:
np.sum(result)

485

## 배열(행렬)의 생성
- 0차원부터 3차원까지로 구성

In [29]:
temp_arr = np.array(30)
print(temp_arr)
print(type(temp_arr))
print()
print(temp_arr.shape)

30
<class 'numpy.ndarray'>

()


In [31]:
temp_arr = np.array([1, 2, 3])
print(temp_arr.shape)
print(temp_arr.ndim)  # 1차원 배열

(3,)
1


## 2차원
- 정형 데이터(엑셀 데이터)

In [35]:
temp_arr = np.array([[1, 2, 3],[4, 5, 6,]])
print(temp_arr.shape)
print(temp_arr.ndim)  # 1차원 배열

(2, 3)
2


## 3차원 데이터
- 이미지 데이터

In [34]:
temp_arr = np.array([[[1, 2, 3],[4, 5, 6,]],[[1, 2, 3],[4, 5, 6,]]])
print(temp_arr.shape)
print(temp_arr.ndim) 

(2, 2, 3)
3


In [39]:
temp_arr = np.array([1, 2, 3, 4], ndmin = 3)
print(temp_arr.shape)
print(temp_arr.ndim)

(1, 1, 4)
3


## 배열 생성의 다양한 방법들
- 모두 0으로 채운다

In [45]:
temp_arr = np.zeros((5, 10))
temp_arr.dtype  #배열 원소가 실수형 타입 1.,1.,

dtype('float64')

In [46]:
temp_arr = np.ones((5, 10))
temp_arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

- 임의의 상수값으로 채운다

In [47]:
temp_arr = np.full((2, 3), 10)
temp_arr

array([[10, 10, 10],
       [10, 10, 10]])

- 최소 및 최대 숫자의 범위를 정해두고, 구간별로 값을 생성하는 코드를 작성함

In [50]:
temp_arr = np.linspace(5, 1000, 5)  ## 5와 10사이에 5개의 숫자가 나와야 함
temp_arr

array([   5.  ,  253.75,  502.5 ,  751.25, 1000.  ])

- 범위를 구하는 배열
- np.arange()

In [52]:
temp_arr = np.arange(1, 100, 4)
temp_arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

- 임의의 난수 생성 (3가지 방법이 있음)

In [55]:
from numpy.random import rand
x = rand()
print(x)

0.9448760451352095


In [53]:
from numpy import random

x = random.rand()
print(x)

0.3749271402894182


In [54]:
import numpy as np
x = np.random.rand()
print(x)

0.980443248378877


## 배열 연산
- 덧셈 : np.add()
- 뺄셈 : np.subtract()
- 곱셈 : np.muptiply()
- 나눗셈 : np.divide()

In [57]:
import numpy as np

array_01 = np.array([1, 2, 3]) 
array_02 = np.array([10, 20, 30]) 
## 덧셈
result = np.add(array_01, array_02)
result

array([11, 22, 33])

In [58]:
# 뺄셈
result = np.subtract(array_01, array_02)
result

array([ -9, -18, -27])

In [59]:
# 곱셈
result = np.multiply(array_01, array_02)
result

array([10, 40, 90])

In [60]:
#나눗셈
result = np.divide(array_01, array_02)
result

array([0.1, 0.1, 0.1])

In [61]:
array_01 = np.array([1, 2, 3])
array_02 = np.array([1, 2, 3])

result = np.power(array_01, array_02)
print(result)

[ 1  4 27]


## 소숫점 정렬
- 소수점 절삭

- 프로그램 코드는 실행속도를 체크
- 어떤 함수가 속도가 빠른지를 체크해서 시간 절약

In [70]:
%%time

temp_arr = np.trunc([-1.23, 1.23])
print(temp_arr)

[-1.  1.]
CPU times: user 1.75 ms, sys: 0 ns, total: 1.75 ms
Wall time: 1.69 ms


In [71]:
%%time

temp_arr = np.fix([-1.23, 1.23])
print(temp_arr)

[-1.  1.]
CPU times: user 1.61 ms, sys: 0 ns, total: 1.61 ms
Wall time: 1.61 ms


- 소수점 자리에서 반올림

In [66]:
temp_arr = np.around([-1.123131, 1.123131], 3)
temp_arr

array([-1.123,  1.123])

In [67]:
temp_arr = np.round([-1.123131, 1.123131], 3)
temp_arr

array([-1.123,  1.123])

- 소수점을 모두

In [72]:
temp_arr = np.floor([-1.23456, 1.23456])
print(temp_arr)

[-2.  1.]


In [75]:
import time

start_time = time.time()  # 현재 시간을 저장
# 실행시간을 측정하고자 하는 코드

temp_arr = np.floor([-1.23456, 1.23456])
print(temp_arr)


end_time = time.time()  # 현재 시간을 저장


elapsed_time = end_time - start_time  # 코드 실행 시간 계산

print("코드 실행 시간: ", elapsed_time, "초")



[-2.  1.]
코드 실행 시간:  0.0014870166778564453 초


## 조건문
- where : 조건식 1개일 때 활용
- select : 다중조건일 때 활용

In [77]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- np.where

In [78]:
np.where(temp_arr < 5, temp_arr, 10*temp_arr)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

- np.select(유용한 함수, 자주 이용됨)

In [80]:
temp_arr = np.arange(10)
cond_list = [temp_arr>5, temp_arr <2]

choice_list = [temp_arr *3, temp_arr + 10]

np.select(cond_list, choice_list, default=temp_arr)

array([10, 11,  2,  3,  4,  5, 18, 21, 24, 27])